# Generated by Django 5.2.4 on 2025-07-23 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название лота')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начальная цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выставления')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено для показа')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('mobile_phone', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('reestr_number', models.CharField(blank=True, max_length=6, null=True, verbose_name='Реестровый номер')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('lot_title', models.CharField(max_length=200, verbose_name='Название лота')),
                ('lot_description', models.TextField(verbose_name='Описание лота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('approved', 'Одобрена (Лот создан)'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('privacy_policy_accepted', models.BooleanField(default=False, verbose_name='Согласие на обработку ПД')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закрепить новость')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Зимний бал', max_length=100, verbose_name='Главный заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подпись под заголовком')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_name', models.CharField(max_length=150, verbose_name='ФИО/Псевдоним участника')),
                ('bidder_email', models.EmailField(max_length=254, verbose_name='Электронная почта участника')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ставки')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='mainapp.lot', verbose_name='Лот')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lot_media/')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='mainapp.lot')),
                ('lot_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='mainapp.lotrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PostMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_media/', verbose_name='Файл')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='mainapp.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.tag', verbose_name='Теги'),
        ),
    ]
