# Generated by Django 5.2.4 on 2025-07-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='auction_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для уведомлений с аукциона'),
        ),
    ]
